### ISSUE TITLE
Ignore .idea

### ISSUE THREAD

**Issue by Piasy** [Luolc/EmojiRain#1]
And `ohters` -> `others`.

**Comment by Luolc** [comment]
Thx~ Not very experienced about which files should be ignore in a project. Are there any articles about this recommended? :D

**Comment by Piasy** [comment]
In my opinion, those not maintained by human, should be ignored :)

**Comment by Luolc** [comment]
hah, nice idea

**Comment by SpongeBobSun** [comment]
And maybe `emoji raining` -> `raining emoji` ?

**Comment by Luolc** [comment]
@SpongeBobSun emm, I am not good at English :P Feel free to point out my typo mistakes, and PR is welcome :D

**Comment by SpongeBobSun** [comment]
Ha, nice project by the way.

**Comment by Luolc** [comment]
@SpongeBobSun thx bro. :P

**Comment by Luolc** [comment]
Already ignored .idea and fix some typo in README.
