### ISSUE TITLE
库里包含了RxJava

### ISSUE THREAD

**Issue by ssyijiu** [Luolc/EmojiRain#2]
一个挺nice的库，但是看到库里使用了Rx的东西，这。。我们项目没有用到Rx，不想因为这个引入Rx，感觉一个库应该尽量少的依赖其他库，所以来提个建议。

**Comment by Luolc** [comment]
@ssyijiu 嗯好的，最开始这个repo只是自己写着玩一玩给几个小伙伴体验一下。很多都没有考虑周全，如果有空的话我写一版没有用到rx的版本吧~

**Comment by ssyijiu** [comment]
恩恩~ ，Issue 我关啦 :)
