### ISSUE TITLE
有多少Emoji表情

### ISSUE THREAD

**Issue by YadoEmoji** [Luolc/EmojiRain#3]
如上

**Comment by Luolc** [comment]
表情是需要自己提供资源的呀，这个lib只是向上封装了addEmoji这个方法，需要用什么是自定义的。Emoji的标准有那么多套，每一套都有数百个表情，如果全要加上这个可要好几M，这显然不是一个Android lib应该有的样子，我想没有任何开发者会为了这么小的一个feature给自己的安装包一下子增加数M吧。
