### ISSUE TITLE
怎么不能设置在onResume里面自启动啊？

### ISSUE THREAD

**Issue by JacksonCheney** [Luolc/EmojiRain#4]
如上，我准备写一个在onResume里面自启动的，然后点击动画停止

**Comment by Luolc** [comment]
能提供一下可以复现出bug的代码嘛。你可以尝试一下clone project，在sample的MainActivity里面加上一个onResume，里面只加一个`mContainer.startDropping()`，我这边是正常的。你可以试试这种情况下会不会出问题。

**Comment by Luolc** [comment]
No further info.
