### ISSUE TITLE
碎片个数增多，频率加快，界面就会很卡怎么解决

### ISSUE THREAD

**Issue by Alpha-chen** [Luolc/EmojiRain#5]

**Comment by Luolc** [comment]
能提供下参数嘛。对 GC 是做了比较多的优化的，测试过正常的设置甚至内存都没有明显突升。

**Comment by Alpha-chen** [comment]
设置参数依次是:
5
7200
7200
500

**Comment by Luolc** [comment]
不大应该啊。README 里的 gif 里的参数比你这个的还要吃内存，但是表现很良好。Demo 的参数我用国内主流品牌的千元以下机都测试过没有出现卡顿。

方便的话可以 clone 下来这个仓库然后安装一下 sample app 试一下，可以比较方便的测试各种参数。如果 README demo 里的参数在你的真机上也卡顿的话那确实是硬件的问题了。如果不卡顿那就得查代码了。

**Comment by Alpha-chen** [comment]
我直接clone的代码运行的。  我在调试看看。另外还有一个问题，  让动画 循环 掉落，如何设置

**Comment by Luolc** [comment]
如果循环掉落指的是不停的掉的话把持续时间设置一个特别大的值就好，然后在需要停的时候调用 stop

**Comment by Alpha-chen** [comment]
就是要不停的掉落，界面不销毁就一致掉落，

**Comment by Luolc** [comment]
那就设置个很大的数就好

**Comment by Alpha-chen** [comment]
PercentFrameLayout 这个 要引入拿个 jar包？

**Comment by Luolc** [comment]
com.android.support:percent
